runtime: python38


handlers:
# frontend
- url: /
  static_dir: build/
- url: /
  static_files: build/index.html
  upload: build/index.html


# backend
- url: /.*
  script: auto

  
entrypoint: python app.py

env: flex

network:
  session_affinity: true
